version: '3.8'
services:
  ceversi:
    init: true
    stop_signal: SIGTERM
    stop_grace_period: 30s
    network_mode: "host"
    build: .
    ports:
      - "31744:31744"
    volumes:
      - ./server.crt:/app/server.crt
      - ./server.key:/app/server.key
      - ./index.html:/app/index.html
      - ./style.css:/app/style.css
      - ./script.js:/app/script.js
      - /opt/ceversi/othello.db:/app/othello.db
    restart: always
